name: rampage_html
version: 0.1.0

description: |
  Browser API bindings, built around JS interop, providing Web Component support
  with a friendly API surface resembling dart:html

homepage: https://rampage-dart.github.io
repository: https://github.com/rampage-dart/rampage
issue_tracker: https://github.com/rampage-dart/rampage/issues

topics:
  - web
  - html

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.10.4
  build_web_compilers: ^4.4.6
  lints: ^6.0.0
