name: rampage_html

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  js: ^0.6.1+1
  meta: ^1.1.7
  rampage_browser_interop:
    path: ../browser-interop

dev_dependencies:
  build_runner: ^1.5.2
  build_web_compilers: ^2.1.1
